# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudagent < Formula
  desc "The simple and easy-to-use program designed to watch user activity for Cloud Providers."
  homepage "http://github.com/pPrecel/cloudagent"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pPrecel/cloudagent/releases/download/v0.2.1/cloudagent_0.2.1_darwin_x86_64.tar.gz"
      sha256 "06af98164ad37eb6bfdcc538071a860a0b65c06b2b3ef2bb7a65452c61a3474d"

      def install
        bin.install "cloudagent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pPrecel/cloudagent/releases/download/v0.2.1/cloudagent_0.2.1_darwin_arm64.tar.gz"
      sha256 "f92023c064786ef901718aca3bd3c1f208ffcbf3064dd14f4d970effb31b11bd"

      def install
        bin.install "cloudagent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pPrecel/cloudagent/releases/download/v0.2.1/cloudagent_0.2.1_linux_x86_64.tar.gz"
      sha256 "fbcd8187b12c3f58dfe41aefd79b99d101f6bf55a110de0667e93890f23811dd"

      def install
        bin.install "cloudagent"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pPrecel/cloudagent/releases/download/v0.2.1/cloudagent_0.2.1_linux_armv7.tar.gz"
      sha256 "06900204e5a27bfb0b741de5920893d620d3fa32acde014a28d8d31abf4b03c6"

      def install
        bin.install "cloudagent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pPrecel/cloudagent/releases/download/v0.2.1/cloudagent_0.2.1_linux_arm64.tar.gz"
      sha256 "b7952b94cbcb765b8e7b53f56faec0865dac865fed4acba5213cd288d8bd83ae"

      def install
        bin.install "cloudagent"
      end
    end
  end

  plist_options :startup => false

  def plist; <<~EOS
    system "#{bin}/cloudagent generate plist"

  EOS
  end

  test do
    system "#{bin}/cloudagent"
  end
end
