# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudagent < Formula
  desc "The simple and easy-to-use program designed to watch user activity for Cloud Providers."
  homepage "http://github.com/pPrecel/cloudagent"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pPrecel/cloudagent/releases/download/v0.2.1/cloudagent_0.2.1_darwin_x86_64.tar.gz"
      sha256 "264112f64547cdd25ed67d2e96d570bcc318c77f8463997c1617d66929c1093f"

      def install
        bin.install "cloudagent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pPrecel/cloudagent/releases/download/v0.2.1/cloudagent_0.2.1_darwin_arm64.tar.gz"
      sha256 "fde704f27113ff23ca1c2db67a7db61cffa037a4936dfe2166465b8cf1db1f05"

      def install
        bin.install "cloudagent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pPrecel/cloudagent/releases/download/v0.2.1/cloudagent_0.2.1_linux_arm64.tar.gz"
      sha256 "950d9cff9170cf67d0b53db273c1e6c95220a486e228e918bebd674da8816e34"

      def install
        bin.install "cloudagent"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pPrecel/cloudagent/releases/download/v0.2.1/cloudagent_0.2.1_linux_x86_64.tar.gz"
      sha256 "52356411e78bc87d34d8f61fef4a5bc9687caf1b12b278ce4e68c3629d0b27d1"

      def install
        bin.install "cloudagent"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pPrecel/cloudagent/releases/download/v0.2.1/cloudagent_0.2.1_linux_armv7.tar.gz"
      sha256 "04794488cdcbae1385a3f2a147d623420750f6d29a88c8efc38ec7a4a4d20d29"

      def install
        bin.install "cloudagent"
      end
    end
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>EnvironmentVariables</key>
        <dict>
                <key>PATH</key>
                <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:</string>
        </dict>
        <key>Label</key>
        <string>com.pPrecel.cloudagent.agent.plist</string>
        <key>ProgramArguments</key>
        <array>
                <string>/usr/local/bin/cloudagent</string>
                <string>serve</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        <key>KeepAlive</key>
        <true/>
        <key>StandardOutPath</key>
        <string>/tmp/cloudagent/cloudagent.stdout</string>
</dict>
</plist>

  EOS
  end

  test do
    system "#{bin}/cloudagent"
  end
end
