# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PkupGen < Formula
  desc "Simple tool to generate PKUP artifacts."
  homepage "http://github.com/pPrecel/pkup-gen"
  version "4.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pPrecel/pkup-gen/releases/download/4.2.0/pkup-gen_4.2.0_darwin_arm64.tar.gz"
      sha256 "073ba9be10d2c6878bacf99d5b005b609166412595d789a8f2a4cdce7b35bef7"

      def install
        bin.install "pkup"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pPrecel/pkup-gen/releases/download/4.2.0/pkup-gen_4.2.0_darwin_amd64.tar.gz"
      sha256 "8c33690065ae88fb36617426da8f061ec9a31ef1c60939bcb1d008dfbf14d1fc"

      def install
        bin.install "pkup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pPrecel/pkup-gen/releases/download/4.2.0/pkup-gen_4.2.0_linux_armv7.tar.gz"
      sha256 "40adb2a72c36d813df1cbfba0a0fdb90347cb006e8d0f9de520a915f7c11f25e"

      def install
        bin.install "pkup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pPrecel/pkup-gen/releases/download/4.2.0/pkup-gen_4.2.0_linux_arm64.tar.gz"
      sha256 "37ccdfd4b3310050483d17b60bf4d272dd960adb4032ab1e84ca9f039ea59a86"

      def install
        bin.install "pkup"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pPrecel/pkup-gen/releases/download/4.2.0/pkup-gen_4.2.0_linux_amd64.tar.gz"
      sha256 "ead27cc530f281003fbf2e463aa16955912ae0144bd03430da0368218597b039"

      def install
        bin.install "pkup"
      end
    end
  end

  test do
    system "#{bin}/pkup"
  end
end
