# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PkupGen < Formula
  desc "Simple tool to generate PKUP artifacts."
  homepage "http://github.com/pPrecel/pkup-gen"
  version "4.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pPrecel/pkup-gen/releases/download/4.1.1/pkup-gen_4.1.1_darwin_arm64.tar.gz"
      sha256 "64717a672282628809758e6fe7663b2b1c0c0ba192019e06d96c4bf7b59157c3"

      def install
        bin.install "pkup"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pPrecel/pkup-gen/releases/download/4.1.1/pkup-gen_4.1.1_darwin_amd64.tar.gz"
      sha256 "fc10d424508fab2c75921e7f8b5626ade222bd5a065d7789c05a0bfcf556049b"

      def install
        bin.install "pkup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pPrecel/pkup-gen/releases/download/4.1.1/pkup-gen_4.1.1_linux_arm64.tar.gz"
      sha256 "b25346881008617cfe8cc9e7066d7e85242a5916d562c6be89d6e63b6c5c2998"

      def install
        bin.install "pkup"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pPrecel/pkup-gen/releases/download/4.1.1/pkup-gen_4.1.1_linux_amd64.tar.gz"
      sha256 "5dda36ddf2489206f166e58dec0aba6218035093685ee2505ed26c16a9fa8761"

      def install
        bin.install "pkup"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pPrecel/pkup-gen/releases/download/4.1.1/pkup-gen_4.1.1_linux_armv7.tar.gz"
      sha256 "87d4134529e611895ebe4c3c3b5edacb5706bb6630bc86e56cfd76d093764b59"

      def install
        bin.install "pkup"
      end
    end
  end

  test do
    system "#{bin}/pkup"
  end
end
